#!/bin/bash

#SBATCH --partition=gpu_titanrtx_shared
#SBATCH --gres=gpu:titanrtx:4
#SBATCH --job-name=train_scannet
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=24
#SBATCH --time=24:00:00
#SBATCH --mem=64000M
#SBATCH --output=job_logs/train_scannet_fulldataset_september.out

module purge
module load 2021
module load CUDA/11.3.1

source activate m2f

cd $HOME/mask2former/Mask2Former
python train_net.py \
  --config-file configs/scannet/semantic-segmentation/swin/maskformer2_swin_large_IN21k_384_bs16_160k_res640.yaml \
  --num-gpus 4 SOLVER.IMS_PER_BATCH 12 SOLVER.BASE_LR 0.0001 SOLVER.MAX_ITER 100000 \
  OUTPUT_DIR ./output/swin_large_fullscannet_september MODEL.WEIGHTS https://dl.fbaipublicfiles.com/maskformer/mask2former/ade20k/semantic/maskformer2_swin_large_IN21k_384_bs16_160k_res640/model_final_6b4a3a.pkl
