#!/bin/bash

#SBATCH --partition=gpu_titanrtx_shared
#SBATCH --gres=gpu:4
#SBATCH --job-name=swin_l
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=24
#SBATCH --time=24:00:00
#SBATCH --mem=90000M
#SBATCH --output=job_logs/swin_l_22k_bs16_crop640.out

module purge
source activate m2f

cd $HOME/mask2former/Mask2Former
python train_net.py \
  --config-file configs/scannet25k/semantic-segmentation/swin/maskformer2_swin_large_IN21k_384_bs16_22k_res640_smallcrop.yaml \
  --num-gpus 4 SOLVER.IMS_PER_BATCH 16 SOLVER.BASE_LR 0.0001 SOLVER.MAX_ITER 22000 \
  OUTPUT_DIR /project/fsun/mask2former/output/swin_l_22k_bs16_crop640 MODEL.WEIGHTS https://dl.fbaipublicfiles.com/maskformer/mask2former/ade20k/semantic/maskformer2_swin_large_IN21k_384_bs16_160k_res640/model_final_6b4a3a.pkl \
  TEST.EVAL_PERIOD 5000
