#!/bin/bash

#SBATCH --partition=gpu_titanrtx_shared
#SBATCH --gres=gpu:4
#SBATCH --job-name=swin_l_train
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=24
#SBATCH --time=120:00:00
#SBATCH --mem=90000M
#SBATCH --output=job_logs/train_scannet_unbiased_swin_l_fromImageNet.out

module purge
source activate m2f

cd $HOME/mask2former/Mask2Former
python train_net.py \
  --config-file configs/scannet25k/semantic-segmentation/swin/maskformer2_swin_large_IN21k_384_bs16_160k_res640.yaml \
  --num-gpus 4 SOLVER.IMS_PER_BATCH 12 SOLVER.BASE_LR 0.0001 SOLVER.MAX_ITER 160000 \
  OUTPUT_DIR ./output/scannet_unbiased_swin_l_fromImageNet MODEL.WEIGHTS tools/swin_large_patch4_window12_384_22k.pkl \
  TEST.EVAL_PERIOD 5000
